-- AUTO-GENERATED by docker/scripts/convert_migrations.py
-- Do not edit by hand. Re-run the converter to regenerate.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS grc_pulse;
SET search_path TO grc_pulse, public;

-- ===== grc-pulse/migrations/0001_initial_schema.sql =====






CREATE TABLE IF NOT EXISTS grc_pulse.organizations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    industry TEXT,
    size TEXT CHECK (size IN ('startup', 'smb', 'enterprise')),
    subscription_tier TEXT DEFAULT 'starter',
    settings TEXT DEFAULT '{}',
    logo_url TEXT,
    compliance_frameworks TEXT DEFAULT '[]',
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    is_active INTEGER DEFAULT 1
);


CREATE TABLE IF NOT EXISTS grc_pulse.users (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    email TEXT NOT NULL,
    password_hash TEXT,
    first_name TEXT,
    last_name TEXT,
    display_name TEXT,
    avatar_url TEXT,
    job_title TEXT,
    department TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'pending')),
    role TEXT DEFAULT 'analyst' CHECK (role IN ('super_admin', 'org_admin', 'ciso', 'executive', 'grc_manager', 'security_lead', 'analyst', 'auditor', 'pentester', 'viewer', 'vendor')),
    last_login_at TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    UNIQUE(organization_id, email)
);


CREATE TABLE IF NOT EXISTS grc_pulse.business_units (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name TEXT NOT NULL,
    description TEXT,
    parent_id TEXT REFERENCES grc_pulse.business_units(id) DEFERRABLE INITIALLY DEFERRED,
    head_user_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    annual_revenue DOUBLE PRECISION,
    employee_count INTEGER,
    is_revenue_generating INTEGER DEFAULT 0,
    criticality TEXT DEFAULT 'medium' CHECK (criticality IN ('critical', 'high', 'medium', 'low', 'informational')),
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.business_processes (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    business_unit_id TEXT REFERENCES grc_pulse.business_units(id) DEFERRABLE INITIALLY DEFERRED,
    name TEXT NOT NULL,
    description TEXT,
    process_owner_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    criticality TEXT DEFAULT 'medium' CHECK (criticality IN ('critical', 'high', 'medium', 'low', 'informational')),
    is_revenue_generating INTEGER DEFAULT 0,
    is_customer_facing INTEGER DEFAULT 0,
    is_regulatory_required INTEGER DEFAULT 0,
    revenue_impact_per_hour DOUBLE PRECISION DEFAULT 0,
    regulatory_fine_exposure DOUBLE PRECISION DEFAULT 0,
    rto_hours INTEGER,
    rpo_hours INTEGER,
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.assets (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    external_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    asset_type TEXT NOT NULL CHECK (asset_type IN ('server', 'database', 'application', 'network_device', 'container', 'serverless', 'storage', 'endpoint', 'iot_device', 'other')),
    cloud_provider TEXT CHECK (cloud_provider IN ('aws', 'azure', 'gcp', 'oracle', 'on_premise', 'hybrid', 'other')),
    cloud_account_id TEXT,
    region TEXT,
    criticality TEXT DEFAULT 'medium' CHECK (criticality IN ('critical', 'high', 'medium', 'low', 'informational')),
    data_classification TEXT CHECK (data_classification IN ('public', 'internal', 'confidential', 'restricted')),
    contains_pii INTEGER DEFAULT 0,
    contains_phi INTEGER DEFAULT 0,
    contains_pci INTEGER DEFAULT 0,
    ip_address TEXT,
    hostname TEXT,
    owner_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    owner_team TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'decommissioned', 'pending')),
    tags TEXT DEFAULT '{}',
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.asset_relationships (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    source_asset_id TEXT NOT NULL REFERENCES grc_pulse.assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    target_asset_id TEXT NOT NULL REFERENCES grc_pulse.assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    relationship_type TEXT NOT NULL CHECK (relationship_type IN ('depends_on', 'connects_to', 'hosts', 'stores_data_in')),
    metadata TEXT DEFAULT '{}',
    created_at TEXT DEFAULT now(),
    UNIQUE(source_asset_id, target_asset_id, relationship_type)
);


CREATE TABLE IF NOT EXISTS grc_pulse.asset_process_mappings (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    asset_id TEXT NOT NULL REFERENCES grc_pulse.assets(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    business_process_id TEXT NOT NULL REFERENCES grc_pulse.business_processes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    dependency_type TEXT DEFAULT 'supports' CHECK (dependency_type IN ('critical', 'supports', 'optional')),
    impact_if_unavailable TEXT,
    created_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE(asset_id, business_process_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.vendors (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name TEXT NOT NULL,
    legal_name TEXT,
    description TEXT,
    website TEXT,
    industry TEXT,
    vendor_tier TEXT DEFAULT 'medium' CHECK (vendor_tier IN ('critical', 'high', 'medium', 'low')),
    vendor_type TEXT,
    has_data_access INTEGER DEFAULT 0,
    data_types_accessed TEXT DEFAULT '[]',
    data_residency_countries TEXT DEFAULT '[]',
    contract_start_date TEXT,
    contract_end_date TEXT,
    contract_value DOUBLE PRECISION,
    primary_contact_name TEXT,
    primary_contact_email TEXT,
    primary_contact_phone TEXT,
    inherent_risk_score DOUBLE PRECISION,
    current_risk_score DOUBLE PRECISION,
    external_risk_score DOUBLE PRECISION,
    certifications TEXT DEFAULT '[]',
    status TEXT DEFAULT 'prospect' CHECK (status IN ('prospect', 'active', 'under_review', 'suspended', 'terminated', 'archived')),
    last_assessment_date TEXT,
    next_assessment_due TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.vendor_process_mappings (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    vendor_id TEXT NOT NULL REFERENCES grc_pulse.vendors(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    business_process_id TEXT NOT NULL REFERENCES grc_pulse.business_processes(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    dependency_level TEXT DEFAULT 'supports' CHECK (dependency_level IN ('critical', 'supports', 'optional')),
    service_description TEXT,
    failover_available INTEGER DEFAULT 0,
    created_at TEXT DEFAULT now(),
    UNIQUE(vendor_id, business_process_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.vendor_incidents (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    vendor_id TEXT NOT NULL REFERENCES grc_pulse.vendors(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    incident_type TEXT CHECK (incident_type IN ('breach', 'outage', 'compliance_violation', 'other')),
    severity TEXT CHECK (severity IN ('critical', 'high', 'medium', 'low', 'informational')),
    title TEXT NOT NULL,
    description TEXT,
    source TEXT,
    source_url TEXT,
    data_compromised INTEGER DEFAULT 0,
    service_affected INTEGER DEFAULT 0,
    our_data_affected INTEGER DEFAULT 0,
    estimated_impact TEXT,
    vendor_response TEXT,
    our_actions TEXT DEFAULT '[]',
    status TEXT DEFAULT 'investigating' CHECK (status IN ('investigating', 'monitoring', 'resolved', 'closed')),
    legal_notified INTEGER DEFAULT 0,
    legal_notified_at TEXT,
    executives_notified INTEGER DEFAULT 0,
    detected_at TEXT,
    resolved_at TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.risk_items (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    title TEXT NOT NULL,
    description TEXT,
    risk_source TEXT NOT NULL CHECK (risk_source IN ('vulnerability_scan', 'penetration_test', 'audit_finding', 'self_assessment', 'vendor_assessment', 'threat_intel', 'incident', 'manual', 'ai_detected')),
    external_reference TEXT,
    category TEXT CHECK (category IN ('vulnerability', 'configuration', 'compliance', 'operational')),
    subcategory TEXT,
    affected_asset_id TEXT REFERENCES grc_pulse.assets(id) DEFERRABLE INITIALLY DEFERRED,
    affected_vendor_id TEXT REFERENCES grc_pulse.vendors(id) DEFERRABLE INITIALLY DEFERRED,
    affected_control_id TEXT,
    inherent_likelihood DOUBLE PRECISION CHECK (inherent_likelihood >= 0 AND inherent_likelihood <= 1),
    inherent_impact DOUBLE PRECISION CHECK (inherent_impact >= 0 AND inherent_impact <= 1),
    inherent_score DOUBLE PRECISION,
    residual_likelihood DOUBLE PRECISION,
    residual_impact DOUBLE PRECISION,
    residual_score DOUBLE PRECISION,
    business_impact_score DOUBLE PRECISION,
    financial_exposure DOUBLE PRECISION,
    context_priority_score DOUBLE PRECISION,
    context_priority_reason TEXT,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'mitigated', 'accepted', 'transferred', 'closed', 'false_positive')),
    assignee_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    due_date TEXT,
    remediation_plan TEXT,
    remediation_cost_estimate DOUBLE PRECISION,
    remediation_effort_days INTEGER,
    evidence_urls TEXT DEFAULT '[]',
    ai_analysis TEXT DEFAULT '{}',
    ai_suggested_controls TEXT DEFAULT '[]',
    discovered_at TEXT DEFAULT now(),
    last_assessed_at TEXT,
    resolved_at TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.risk_history (
    id TEXT PRIMARY KEY,
    risk_id TEXT NOT NULL REFERENCES grc_pulse.risk_items(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    changed_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    change_type TEXT,
    previous_value TEXT,
    new_value TEXT,
    notes TEXT,
    created_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.compliance_frameworks (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    version TEXT,
    authority TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.controls (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    control_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    control_type TEXT CHECK (control_type IN ('preventive', 'detective', 'corrective')),
    implementation_type TEXT CHECK (implementation_type IN ('technical', 'administrative', 'physical')),
    owner_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    owner_team TEXT,
    implementation_status TEXT DEFAULT 'not_started' CHECK (implementation_status IN ('not_started', 'in_progress', 'implemented', 'not_applicable')),
    implementation_evidence TEXT,
    implementation_date TEXT,
    effectiveness_rating TEXT CHECK (effectiveness_rating IN ('effective', 'partially_effective', 'ineffective', 'not_tested')),
    last_tested_date TEXT,
    next_test_due TEXT,
    test_frequency_days INTEGER DEFAULT 365,
    policy_document_url TEXT,
    procedure_document_url TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE(organization_id, control_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.policies (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    title TEXT NOT NULL,
    policy_number TEXT,
    version TEXT DEFAULT '1.0',
    category TEXT,
    policy_type TEXT CHECK (policy_type IN ('policy', 'standard', 'procedure', 'guideline')),
    content TEXT,
    summary TEXT,
    document_url TEXT,
    owner_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    approver_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'pending_approval', 'approved', 'archived')),
    effective_date TEXT,
    review_date TEXT,
    next_review_date TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.audit_logs (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES grc_pulse.organizations(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    user_id TEXT REFERENCES grc_pulse.users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    previous_state TEXT,
    new_state TEXT,
    ip_address TEXT,
    user_agent TEXT,
    status TEXT DEFAULT 'success',
    error_message TEXT,
    created_at TEXT DEFAULT now()
);


-- Invitation tokens for the "Add Team Member" flow (org admin invites a user,
-- who then sets their password via the invite link). Referenced by the
-- application as `invitation_tokens`.
CREATE TABLE IF NOT EXISTS grc_pulse.invitation_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES grc_pulse.users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    token TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_by TEXT REFERENCES grc_pulse.users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    created_at TEXT DEFAULT now()
);


-- Application-level audit trail written by the user-management endpoints.
-- Distinct from the richer `audit_logs` table above: the app writes to
-- `audit_log` (singular) with entity_type/entity_id/details columns.
CREATE TABLE IF NOT EXISTS grc_pulse.audit_log (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES grc_pulse.organizations(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    user_id TEXT REFERENCES grc_pulse.users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    details TEXT,
    created_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.notifications (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    user_id TEXT REFERENCES grc_pulse.users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT,
    link_type TEXT,
    link_id TEXT,
    link_url TEXT,
    is_read INTEGER DEFAULT 0,
    read_at TEXT,
    priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    created_at TEXT DEFAULT now(),
    expires_at TEXT
);


CREATE INDEX IF NOT EXISTS idx_users_org ON grc_pulse.users(organization_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON grc_pulse.users(email);
CREATE INDEX IF NOT EXISTS idx_assets_org ON grc_pulse.assets(organization_id);
CREATE INDEX IF NOT EXISTS idx_assets_type ON grc_pulse.assets(organization_id, asset_type);
CREATE INDEX IF NOT EXISTS idx_assets_criticality ON grc_pulse.assets(organization_id, criticality);
CREATE INDEX IF NOT EXISTS idx_risks_org ON grc_pulse.risk_items(organization_id);
CREATE INDEX IF NOT EXISTS idx_risks_status ON grc_pulse.risk_items(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_risks_priority ON grc_pulse.risk_items(organization_id, context_priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_vendors_org ON grc_pulse.vendors(organization_id);
CREATE INDEX IF NOT EXISTS idx_vendors_tier ON grc_pulse.vendors(organization_id, vendor_tier);
CREATE INDEX IF NOT EXISTS idx_vendor_incidents_vendor ON grc_pulse.vendor_incidents(vendor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_org ON grc_pulse.audit_logs(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_org ON grc_pulse.audit_log(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_token ON grc_pulse.invitation_tokens(token);
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_user ON grc_pulse.invitation_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON grc_pulse.notifications(user_id, is_read);


-- ===== grc-pulse/migrations/0002_maturity_assessment.sql =====







CREATE TABLE IF NOT EXISTS grc_pulse.maturity_assessments (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name TEXT NOT NULL,
    description TEXT,
    assessment_type TEXT DEFAULT 'security' CHECK (assessment_type IN ('security', 'privacy', 'risk', 'compliance')),
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'in_progress', 'completed', 'archived')),
    overall_score DOUBLE PRECISION,
    overall_percentage DOUBLE PRECISION,
    target_score DOUBLE PRECISION DEFAULT 5.0,
    assessor_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    reviewer_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    approved_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    approved_at TEXT,
    assessment_date TEXT DEFAULT now(),
    next_assessment_due TEXT,
    notes TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.maturity_responses (
    id TEXT PRIMARY KEY,
    assessment_id TEXT NOT NULL REFERENCES grc_pulse.maturity_assessments(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    category_id TEXT NOT NULL,
    question_id INTEGER NOT NULL,
    current_score INTEGER CHECK (current_score >= 0 AND current_score <= 5),
    target_score INTEGER DEFAULT 5 CHECK (target_score >= 0 AND target_score <= 5),
    evidence TEXT,
    notes TEXT,
    action_plan TEXT,
    responsible_person TEXT,
    target_date TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    UNIQUE(assessment_id, question_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.maturity_category_scores (
    id TEXT PRIMARY KEY,
    assessment_id TEXT NOT NULL REFERENCES grc_pulse.maturity_assessments(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    category_id TEXT NOT NULL,
    category_name_en TEXT NOT NULL,
    category_name_ar TEXT,
    current_score DOUBLE PRECISION,
    target_score DOUBLE PRECISION DEFAULT 5.0,
    questions_answered INTEGER DEFAULT 0,
    total_questions INTEGER,
    gap_score DOUBLE PRECISION,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    UNIQUE(assessment_id, category_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.maturity_improvement_actions (
    id TEXT PRIMARY KEY,
    assessment_id TEXT NOT NULL REFERENCES grc_pulse.maturity_assessments(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    organization_id TEXT NOT NULL REFERENCES grc_pulse.organizations(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    category_id TEXT NOT NULL,
    question_id INTEGER,
    action_title TEXT NOT NULL,
    action_description TEXT,
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),
    status TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed', 'cancelled', 'deferred')),
    assignee_id TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
    due_date TEXT,
    completed_date TEXT,
    estimated_effort_days INTEGER,
    estimated_cost DOUBLE PRECISION,
    expected_score_improvement DOUBLE PRECISION,
    notes TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    created_by TEXT REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE INDEX IF NOT EXISTS idx_maturity_assessments_org ON grc_pulse.maturity_assessments(organization_id);
CREATE INDEX IF NOT EXISTS idx_maturity_assessments_status ON grc_pulse.maturity_assessments(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_maturity_assessments_date ON grc_pulse.maturity_assessments(organization_id, assessment_date DESC);
CREATE INDEX IF NOT EXISTS idx_maturity_responses_assessment ON grc_pulse.maturity_responses(assessment_id);
CREATE INDEX IF NOT EXISTS idx_maturity_responses_category ON grc_pulse.maturity_responses(assessment_id, category_id);
CREATE INDEX IF NOT EXISTS idx_maturity_category_scores_assessment ON grc_pulse.maturity_category_scores(assessment_id);
CREATE INDEX IF NOT EXISTS idx_maturity_actions_assessment ON grc_pulse.maturity_improvement_actions(assessment_id);
CREATE INDEX IF NOT EXISTS idx_maturity_actions_status ON grc_pulse.maturity_improvement_actions(organization_id, status);


-- ===== grc-pulse/migrations/0003_pentest_sync_support.sql =====









CREATE TABLE IF NOT EXISTS grc_pulse.pentest_sync_log (
    id TEXT PRIMARY KEY,
    sync_type TEXT NOT NULL CHECK (sync_type IN ('create', 'update', 'delete', 'bulk')),
    source_finding_id TEXT NOT NULL,
    source_project_code TEXT,
    target_risk_id TEXT,
    payload TEXT,
    status TEXT DEFAULT 'success' CHECK (status IN ('success', 'failed', 'pending')),
    error_message TEXT,
    synced_at TEXT DEFAULT now()
);


CREATE INDEX IF NOT EXISTS idx_pentest_sync_log_finding ON grc_pulse.pentest_sync_log(source_finding_id);
CREATE INDEX IF NOT EXISTS idx_pentest_sync_log_date ON grc_pulse.pentest_sync_log(synced_at);
CREATE INDEX IF NOT EXISTS idx_pentest_sync_log_status ON grc_pulse.pentest_sync_log(status);


CREATE INDEX IF NOT EXISTS idx_risk_items_source ON grc_pulse.risk_items(risk_source);
CREATE INDEX IF NOT EXISTS idx_risk_items_external_ref ON grc_pulse.risk_items(external_reference);


CREATE OR REPLACE VIEW grc_pulse.pentest_risks_view AS
SELECT 
    r.id,
    r.organization_id,
    r.title,
    r.description,
    r.category,
    r.subcategory,
    r.inherent_likelihood,
    r.inherent_impact,
    r.inherent_score,
    r.context_priority_score,
    r.status,
    r.remediation_plan,
    r.due_date,
    r.external_reference,
    r.ai_analysis,
    r.discovered_at,
    r.created_at,
    r.updated_at,
    a.name as asset_name,
    a.asset_type,
    a.criticality as asset_criticality,
    
    CASE 
        WHEN r.external_reference LIKE 'pentest:%' 
        THEN substr(r.external_reference, 9, position('|' in r.external_reference) - 9)
        ELSE NULL 
    END as source_finding_id,
    CASE 
        WHEN r.external_reference LIKE '%project:%' 
        THEN substr(
            r.external_reference, 
            position('project:' in r.external_reference) + 8,
            position('|' in substr(r.external_reference, position('project:' in r.external_reference))) - 9
        )
        ELSE NULL 
    END as source_project_code
FROM grc_pulse.risk_items r
LEFT JOIN grc_pulse.assets a ON r.affected_asset_id = a.id
WHERE r.risk_source = 'penetration_test';




CREATE OR REPLACE VIEW grc_pulse.pentest_sync_stats AS
SELECT 
    organization_id,
    COUNT(*) as total_risks,
    SUM(CASE WHEN status = 'open' THEN 1 ELSE 0 END) as open_count,
    SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END) as in_progress_count,
    SUM(CASE WHEN status = 'mitigated' THEN 1 ELSE 0 END) as mitigated_count,
    SUM(CASE WHEN status = 'closed' THEN 1 ELSE 0 END) as closed_count,
    SUM(CASE WHEN status = 'accepted' THEN 1 ELSE 0 END) as accepted_count,
    SUM(CASE WHEN inherent_score >= 80 THEN 1 ELSE 0 END) as critical_count,
    SUM(CASE WHEN inherent_score >= 60 AND inherent_score < 80 THEN 1 ELSE 0 END) as high_count,
    SUM(CASE WHEN inherent_score >= 30 AND inherent_score < 60 THEN 1 ELSE 0 END) as medium_count,
    SUM(CASE WHEN inherent_score < 30 THEN 1 ELSE 0 END) as low_count,
    MAX(updated_at) as last_sync_at,
    MIN(created_at) as first_sync_at
FROM grc_pulse.risk_items
WHERE risk_source = 'penetration_test'
GROUP BY organization_id;


-- ===== grc-pulse/migrations/0004_compliance_engine.sql =====













CREATE TABLE IF NOT EXISTS grc_pulse.compliance_frameworks_v2 (
  id TEXT PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,           
  name TEXT NOT NULL,
  version TEXT,                         
  description TEXT,
  authority TEXT,                       
  total_controls INTEGER DEFAULT 0,
  is_core_framework INTEGER DEFAULT 0,  
  is_active INTEGER DEFAULT 1,
  icon TEXT,                            
  color TEXT,                           
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS grc_pulse.control_library (
  id TEXT PRIMARY KEY,
  framework_id TEXT NOT NULL,
  control_id TEXT NOT NULL,             
  control_number TEXT,                  
  title TEXT NOT NULL,
  description TEXT,
  guidance TEXT,                        
  category TEXT,                        
  subcategory TEXT,                     
  control_type TEXT,                    
  is_critical INTEGER DEFAULT 0,        
  weight DOUBLE PRECISION DEFAULT 1.0,              
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(framework_id, control_id)
);



CREATE TABLE IF NOT EXISTS grc_pulse.iso27001_themes (
  id TEXT PRIMARY KEY,
  theme_number INTEGER NOT NULL,        
  name TEXT NOT NULL,                   
  description TEXT,
  control_count INTEGER DEFAULT 0,
  icon TEXT,
  color TEXT
);






CREATE TABLE IF NOT EXISTS grc_pulse.control_mappings (
  id TEXT PRIMARY KEY,
  source_framework_id TEXT NOT NULL,    
  source_control_id TEXT NOT NULL,
  target_framework_id TEXT NOT NULL,
  target_control_id TEXT NOT NULL,
  mapping_type TEXT DEFAULT 'equivalent', 
  mapping_strength DOUBLE PRECISION DEFAULT 1.0,    
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (source_framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (target_framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(source_framework_id, source_control_id, target_framework_id, target_control_id)
);






CREATE TABLE IF NOT EXISTS grc_pulse.org_framework_applicability (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  is_applicable INTEGER DEFAULT 1,      
  applicability_reason TEXT,            
  target_compliance_date DATE,
  certification_status TEXT,            
  certification_date DATE,
  certification_expiry DATE,
  auditor TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, framework_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.control_assessments (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  control_library_id TEXT NOT NULL,     
  
  
  implementation_status TEXT DEFAULT 'not_started',  
  
  
  
  maturity_level INTEGER DEFAULT 0,     
  
  
  assessment_date DATE,
  assessor_id TEXT,
  evidence_description TEXT,
  evidence_urls TEXT DEFAULT '[]',      
  gaps_identified TEXT,
  remediation_plan TEXT,
  remediation_due_date DATE,
  remediation_owner_id TEXT,
  
  
  linked_risk_ids TEXT DEFAULT '[]',    
  
  
  last_audit_date DATE,
  last_audit_result TEXT,
  audit_findings TEXT,
  
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  created_by TEXT,
  
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (control_library_id) REFERENCES grc_pulse.control_library(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (assessor_id) REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (remediation_owner_id) REFERENCES grc_pulse.users(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, control_library_id)
);






CREATE TABLE IF NOT EXISTS grc_pulse.compliance_scores (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  
  
  compliance_score DOUBLE PRECISION DEFAULT 0,      
  maturity_score DOUBLE PRECISION DEFAULT 0,        
  
  
  total_controls INTEGER DEFAULT 0,
  applicable_controls INTEGER DEFAULT 0,
  implemented_controls INTEGER DEFAULT 0,
  partial_controls INTEGER DEFAULT 0,
  not_implemented_controls INTEGER DEFAULT 0,
  not_applicable_controls INTEGER DEFAULT 0,
  
  
  category_scores TEXT DEFAULT '{}',    
  
  
  previous_score DOUBLE PRECISION,
  score_change DOUBLE PRECISION,
  
  
  last_calculated TIMESTAMPTZ,
  calculation_method TEXT DEFAULT 'weighted', 
  
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, framework_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.compliance_history (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  maturity_score DOUBLE PRECISION,
  snapshot_date DATE NOT NULL,
  snapshot_data TEXT,                   
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE INDEX IF NOT EXISTS idx_control_library_framework ON grc_pulse.control_library(framework_id);
CREATE INDEX IF NOT EXISTS idx_control_library_category ON grc_pulse.control_library(category);
CREATE INDEX IF NOT EXISTS idx_control_assessments_org ON grc_pulse.control_assessments(organization_id);
CREATE INDEX IF NOT EXISTS idx_control_assessments_control ON grc_pulse.control_assessments(control_library_id);
CREATE INDEX IF NOT EXISTS idx_control_assessments_status ON grc_pulse.control_assessments(implementation_status);
CREATE INDEX IF NOT EXISTS idx_control_mappings_source ON grc_pulse.control_mappings(source_framework_id, source_control_id);
CREATE INDEX IF NOT EXISTS idx_control_mappings_target ON grc_pulse.control_mappings(target_framework_id, target_control_id);
CREATE INDEX IF NOT EXISTS idx_compliance_scores_org ON grc_pulse.compliance_scores(organization_id);
CREATE INDEX IF NOT EXISTS idx_org_applicability ON grc_pulse.org_framework_applicability(organization_id);






-- ===== grc-pulse/migrations/0006_organization_profile.sql =====






CREATE TABLE IF NOT EXISTS grc_pulse.organization_profile (
  organization_id TEXT PRIMARY KEY,
  company_name TEXT NOT NULL,
  industry TEXT NOT NULL DEFAULT 'technology',
  industry_sector TEXT,
  company_size TEXT DEFAULT 'medium',
  headquarters_region TEXT DEFAULT 'us',
  operating_regions TEXT DEFAULT '["us"]',
  
  
  handles_card_data INTEGER DEFAULT 0,
  handles_health_data INTEGER DEFAULT 0,
  handles_personal_data INTEGER DEFAULT 1,
  handles_financial_data INTEGER DEFAULT 0,
  handles_government_data INTEGER DEFAULT 0,
  
  
  iso_certified INTEGER DEFAULT 0,
  soc2_certified INTEGER DEFAULT 0,
  pci_certified INTEGER DEFAULT 0,
  gdpr_compliant INTEGER DEFAULT 0,
  hipaa_compliant INTEGER DEFAULT 0,
  
  
  risk_appetite TEXT DEFAULT 'moderate',
  security_maturity_target INTEGER DEFAULT 3,
  
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS grc_pulse.framework_applicability (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  is_applicable INTEGER DEFAULT 1,
  applicability_reason TEXT,
  priority INTEGER DEFAULT 3,
  target_score INTEGER DEFAULT 80,
  target_date TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(organization_id, framework_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.soa_entries (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  control_library_id TEXT NOT NULL,
  is_applicable INTEGER DEFAULT 1,
  justification TEXT,
  exclusion_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(organization_id, control_library_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.industry_framework_requirements (
  id TEXT PRIMARY KEY,
  industry TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  is_typically_required INTEGER DEFAULT 0,
  is_recommended INTEGER DEFAULT 1,
  requirement_notes TEXT,
  UNIQUE(industry, framework_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.data_type_framework_requirements (
  id TEXT PRIMARY KEY,
  data_type TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  is_required INTEGER DEFAULT 1,
  requirement_notes TEXT,
  UNIQUE(data_type, framework_id)
);


CREATE TABLE IF NOT EXISTS grc_pulse.region_framework_requirements (
  id TEXT PRIMARY KEY,
  region TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  is_required INTEGER DEFAULT 0,
  is_recommended INTEGER DEFAULT 1,
  requirement_notes TEXT,
  UNIQUE(region, framework_id)
);


-- ===== grc-pulse/migrations/0007_compliance_history.sql =====





CREATE TABLE IF NOT EXISTS grc_pulse.compliance_snapshots (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  framework_id TEXT NOT NULL,
  snapshot_date DATE NOT NULL,
  basic_score INTEGER DEFAULT 0,
  advanced_score INTEGER DEFAULT 0,
  implemented_count INTEGER DEFAULT 0,
  in_progress_count INTEGER DEFAULT 0,
  not_started_count INTEGER DEFAULT 0,
  not_applicable_count INTEGER DEFAULT 0,
  total_controls INTEGER DEFAULT 0,
  avg_maturity DOUBLE PRECISION DEFAULT 0,
  critical_score INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (framework_id) REFERENCES grc_pulse.compliance_frameworks_v2(id) DEFERRABLE INITIALLY DEFERRED
);


CREATE INDEX IF NOT EXISTS idx_compliance_snapshots_org_fw_date 
ON grc_pulse.compliance_snapshots(organization_id, framework_id, snapshot_date);


CREATE TABLE IF NOT EXISTS grc_pulse.domain_snapshots (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  snapshot_date DATE NOT NULL,
  domain_name TEXT NOT NULL,
  basic_score INTEGER DEFAULT 0,
  advanced_score INTEGER DEFAULT 0,
  implemented_count INTEGER DEFAULT 0,
  total_controls INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_domain_snapshots_org_date 
ON grc_pulse.domain_snapshots(organization_id, snapshot_date);


CREATE TABLE IF NOT EXISTS grc_pulse.risk_snapshots (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  snapshot_date DATE NOT NULL,
  total_risks INTEGER DEFAULT 0,
  open_risks INTEGER DEFAULT 0,
  critical_risks INTEGER DEFAULT 0,
  high_risks INTEGER DEFAULT 0,
  medium_risks INTEGER DEFAULT 0,
  low_risks INTEGER DEFAULT 0,
  total_exposure DOUBLE PRECISION DEFAULT 0,
  avg_risk_score DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_risk_snapshots_org_date 
ON grc_pulse.risk_snapshots(organization_id, snapshot_date);


-- ===== grc-pulse/migrations/0009_control_risk_asset_linking.sql =====








CREATE TABLE IF NOT EXISTS grc_pulse.control_risk_mappings (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  control_id TEXT NOT NULL,           
  risk_id TEXT NOT NULL,              
  mapping_type TEXT DEFAULT 'mitigates', 
  effectiveness TEXT DEFAULT 'partial', 
  confidence_score INTEGER DEFAULT 80,  
  notes TEXT,
  is_auto_suggested INTEGER DEFAULT 0,  
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, control_id, risk_id)
);


CREATE INDEX IF NOT EXISTS idx_crm_org_control ON grc_pulse.control_risk_mappings(organization_id, control_id);
CREATE INDEX IF NOT EXISTS idx_crm_org_risk ON grc_pulse.control_risk_mappings(organization_id, risk_id);
CREATE INDEX IF NOT EXISTS idx_crm_mapping_type ON grc_pulse.control_risk_mappings(mapping_type);






CREATE TABLE IF NOT EXISTS grc_pulse.control_asset_mappings (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  control_id TEXT NOT NULL,           
  asset_id TEXT NOT NULL,             
  protection_type TEXT DEFAULT 'protects', 
  coverage TEXT DEFAULT 'partial',    
  notes TEXT,
  is_auto_suggested INTEGER DEFAULT 0,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, control_id, asset_id)
);


CREATE INDEX IF NOT EXISTS idx_cam_org_control ON grc_pulse.control_asset_mappings(organization_id, control_id);
CREATE INDEX IF NOT EXISTS idx_cam_org_asset ON grc_pulse.control_asset_mappings(organization_id, asset_id);






CREATE TABLE IF NOT EXISTS grc_pulse.risk_asset_mappings (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  risk_id TEXT NOT NULL,              
  asset_id TEXT NOT NULL,             
  impact_type TEXT DEFAULT 'affects', 
  impact_level TEXT DEFAULT 'medium', 
  notes TEXT,
  is_auto_suggested INTEGER DEFAULT 0,
  created_by TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (organization_id) REFERENCES grc_pulse.organizations(id) DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(organization_id, risk_id, asset_id)
);


CREATE INDEX IF NOT EXISTS idx_ram_org_risk ON grc_pulse.risk_asset_mappings(organization_id, risk_id);
CREATE INDEX IF NOT EXISTS idx_ram_org_asset ON grc_pulse.risk_asset_mappings(organization_id, asset_id);







CREATE TABLE IF NOT EXISTS grc_pulse.control_risk_suggestions (
  id TEXT PRIMARY KEY,
  control_category TEXT NOT NULL,     
  control_subcategory TEXT,           
  risk_category TEXT NOT NULL,        
  risk_keywords TEXT,                 
  suggestion_weight INTEGER DEFAULT 50, 
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- ===== grc-pulse/migrations/0010_audit_management.sql =====




CREATE TABLE IF NOT EXISTS grc_pulse.audit_programs (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    year INTEGER NOT NULL,
    status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'active', 'completed', 'cancelled')),
    start_date TEXT,
    end_date TEXT,
    audit_manager_id TEXT,
    total_engagements INTEGER DEFAULT 0,
    completed_engagements INTEGER DEFAULT 0,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now()
);


CREATE TABLE IF NOT EXISTS grc_pulse.audit_engagements (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    program_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    audit_type TEXT DEFAULT 'internal' CHECK(audit_type IN ('internal', 'external', 'regulatory', 'compliance', 'operational', 'financial', 'it', 'security')),
    status TEXT DEFAULT 'planned' CHECK(status IN ('planned', 'in_progress', 'fieldwork', 'reporting', 'completed', 'cancelled')),
    priority TEXT DEFAULT 'medium' CHECK(priority IN ('critical', 'high', 'medium', 'low')),
    scope TEXT,
    objectives TEXT,
    lead_auditor_id TEXT,
    lead_auditor_name TEXT,
    start_date TEXT,
    end_date TEXT,
    report_date TEXT,
    department TEXT,
    findings_count INTEGER DEFAULT 0,
    open_findings INTEGER DEFAULT 0,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    FOREIGN KEY (program_id) REFERENCES grc_pulse.audit_programs(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.audit_findings (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    engagement_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    finding_type TEXT DEFAULT 'deficiency' CHECK(finding_type IN ('deficiency', 'weakness', 'observation', 'recommendation', 'non_compliance', 'fraud', 'control_gap')),
    severity TEXT DEFAULT 'medium' CHECK(severity IN ('critical', 'high', 'medium', 'low', 'informational')),
    status TEXT DEFAULT 'open' CHECK(status IN ('open', 'in_progress', 'remediation_planned', 'remediated', 'closed', 'accepted', 'deferred')),
    category TEXT,
    affected_process TEXT,
    affected_department TEXT,
    root_cause TEXT,
    impact TEXT,
    likelihood INTEGER DEFAULT 3 CHECK(likelihood >= 1 AND likelihood <= 5),
    impact_score INTEGER DEFAULT 3 CHECK(impact_score >= 1 AND impact_score <= 5),
    risk_rating TEXT,
    recommendation TEXT,
    management_response TEXT,
    remediation_plan TEXT,
    remediation_owner_id TEXT,
    remediation_owner_name TEXT,
    due_date TEXT,
    closed_date TEXT,
    evidence TEXT,
    related_control_id TEXT,
    related_risk_id TEXT,
    external_reference TEXT,
    created_by TEXT,
    created_at TEXT DEFAULT now(),
    updated_at TEXT DEFAULT now(),
    FOREIGN KEY (engagement_id) REFERENCES grc_pulse.audit_engagements(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS grc_pulse.audit_evidence (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    finding_id TEXT,
    engagement_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    file_type TEXT,
    file_url TEXT,
    uploaded_by TEXT,
    created_at TEXT DEFAULT now(),
    FOREIGN KEY (finding_id) REFERENCES grc_pulse.audit_findings(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (engagement_id) REFERENCES grc_pulse.audit_engagements(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);


CREATE INDEX IF NOT EXISTS idx_audit_programs_org ON grc_pulse.audit_programs(organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_programs_year ON grc_pulse.audit_programs(year);
CREATE INDEX IF NOT EXISTS idx_audit_engagements_org ON grc_pulse.audit_engagements(organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_engagements_program ON grc_pulse.audit_engagements(program_id);
CREATE INDEX IF NOT EXISTS idx_audit_engagements_status ON grc_pulse.audit_engagements(status);
CREATE INDEX IF NOT EXISTS idx_audit_findings_org ON grc_pulse.audit_findings(organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_findings_engagement ON grc_pulse.audit_findings(engagement_id);
CREATE INDEX IF NOT EXISTS idx_audit_findings_status ON grc_pulse.audit_findings(status);
CREATE INDEX IF NOT EXISTS idx_audit_findings_severity ON grc_pulse.audit_findings(severity);
CREATE INDEX IF NOT EXISTS idx_audit_findings_risk ON grc_pulse.audit_findings(related_risk_id);

-- ===== on-prem compatibility: users_new =====
CREATE OR REPLACE VIEW grc_pulse.users_new AS
  SELECT * FROM grc_pulse.users;

-- ===== on-prem compatibility: control_assessments extra columns =====
ALTER TABLE grc_pulse.control_assessments
  ADD COLUMN IF NOT EXISTS manual_override INTEGER DEFAULT 0;
ALTER TABLE grc_pulse.control_assessments
  ADD COLUMN IF NOT EXISTS risk_warnings TEXT;

-- ===== on-prem compatibility: audit_findings.affected_controls =====
ALTER TABLE grc_pulse.audit_findings
  ADD COLUMN IF NOT EXISTS affected_controls TEXT;

