-- AUTO-GENERATED by docker/scripts/convert_migrations.py
-- Do not edit by hand. Re-run the converter to regenerate.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS autoaudit;
SET search_path TO autoaudit, public;

-- ===== autoaudit/src/modules/schema(1).sql =====



CREATE TABLE IF NOT EXISTS autoaudit.sessions (
  id           TEXT PRIMARY KEY,
  org_name     TEXT NOT NULL,
  industry     TEXT NOT NULL,
  size         TEXT NOT NULL,
  lang         TEXT NOT NULL DEFAULT 'en',
  phase        TEXT NOT NULL DEFAULT 'idle',
  ctrl_idx     INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS autoaudit.gap_results (
  id              BIGSERIAL PRIMARY KEY,
  session_id      TEXT NOT NULL,
  ctrl_id         TEXT NOT NULL,
  ctrl_name       TEXT NOT NULL,
  verdict         TEXT NOT NULL,
  finding         TEXT,
  recommendation  TEXT,
  evidence_type   TEXT DEFAULT 'none',
  assessed_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES autoaudit.sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS autoaudit.chat_messages (
  id           BIGSERIAL PRIMARY KEY,
  session_id   TEXT NOT NULL,
  role         TEXT NOT NULL,
  msg_text     TEXT NOT NULL,
  control_id   TEXT,
  control_name TEXT,
  verdict      TEXT,
  file_name    TEXT,
  is_status    INTEGER DEFAULT 0,
  created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES autoaudit.sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_results_session  ON autoaudit.gap_results(session_id);
CREATE INDEX IF NOT EXISTS idx_messages_session ON autoaudit.chat_messages(session_id);









-- Consultant session tables (created via API in the Cloudflare version)
CREATE TABLE IF NOT EXISTS autoaudit.consultant_sessions (
  id          TEXT PRIMARY KEY,
  org         TEXT,
  industry    TEXT,
  lang        TEXT NOT NULL DEFAULT 'en',
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS autoaudit.consultant_messages (
  id          BIGSERIAL PRIMARY KEY,
  session_id  TEXT NOT NULL REFERENCES autoaudit.consultant_sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  role        TEXT NOT NULL,
  msg_text    TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS autoaudit.policy_sessions (
  id           TEXT PRIMARY KEY,
  org_name     TEXT NOT NULL,
  industry     TEXT,
  size         TEXT,
  framework    TEXT,
  policy_type  TEXT,
  policy_ref   TEXT,
  policy_json  TEXT,
  lang         TEXT NOT NULL DEFAULT 'en',
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_consultant_msgs_session ON autoaudit.consultant_messages(session_id);

